# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ineuron-bike

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fb23f45917f646ca948700253e13da6e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a654bc8d83664a0b96bedb4cff2e1c3a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fb23f45917f646ca948700253e13da6e }}/ineuron-bike:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ineuron-bike'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_98b9cfa6606640c0a86a121b42444211 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fb23f45917f646ca948700253e13da6e }}/ineuron-bike:${{ github.sha }}'